services:
- type: web
  name: linebot-ptt-info
  env: python
  repo: https://github.com/LinBoRui/linebot-ptt-info.git
  buildCommand: pip install -r requirements.txt gunicorn
  startCommand: gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
