services:
- type: web
  name: line-bot-ptt-info
  env: python
  repo: https://github.com/LinBoRui/linebot-ptt-info.git
  buildCommand: pip install -r requirements.txt
  startCommand: python3 app.py
  plan: free
  autoDeploy: false
  envVars:
  - key: PYTHON_VERSION
    value: "3.10.8"
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
